# Generated by Django 5.1.7 on 2025-03-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payments_paid_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_way',
            field=models.CharField(blank=True, choices=[('наличные', 'наличные'), ('перевод на счет', 'перевод на счет')], null=True, verbose_name='способ оплаты'),
        ),
    ]
