# Generated by Django 5.1.7 on 2025-03-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payments_payment_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_way',
            field=models.CharField(choices=[('наличные', 'наличные'), ('перевод на счет', 'перевод на счет')], default='наличные', verbose_name='способ оплаты'),
            preserve_default=False,
        ),
    ]
