# Generated by Django 5.1.7 on 2025-03-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payments_payment_way'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
    ]
