# Generated by Django 5.1.7 on 2025-03-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_payments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
