# Generated by Django 5.1.7 on 2025-03-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_payments_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='url'),
        ),
    ]
