# Generated by Django 5.1.7 on 2025-03-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_subscription_course_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['owner'], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['owner'], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
    ]
