# Generated by Django 5.1.7 on 2025-03-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_course_options_alter_lesson_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_subscribed',
        ),
    ]
