# Generated by Django 5.1.7 on 2025-03-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_subscription_course_alter_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payment',
            field=models.IntegerField(default=0, verbose_name='цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='payment',
            field=models.IntegerField(default=0, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
